########################################################################################
# Book settings
title: Основи програмування в "обіймах" Python
author: <a href="mailto:vikvikgrom@gmail.com">Громова В.В.</a>
logo: content/images/logo/logo.png
copyright: "2020"

exclude_patterns: [_*, .*, tools, README.md, content/LICENSE.md, content/wip*]

#description: >-
#  Інструкції до виконання лабораторних робіт
#  з дисципліни "Програмування-1. Основи програмування"

#######################################################################################
# Html settings

html:
  favicon: content/images/logo/favicon.ico
  extra_footer: >-
      This page was created by <a href="https://github.com/kpi-fpm-pma/python-labs-book/graphs/contributors">community</a>.<br />
      "Python" and Python logos are trademarks or registered trademarks of Python Software Fundation.
  home_page_in_navbar: true
  baseurl: https://kpi-fpm-pma.github.io/python-labs-book

#######################################################################################
# Interact link settings
launch_buttons:
  notebook_interface: jupyterlab
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"
  thebe: true

repository:
  url: https://github.com/kpi-fpm-pma/python-labs-book
  branch: main
  path_to_book: ''

#######################################################################################
# Execution settings
execute:
  execute_notebooks: off
  allow_errors: true

#######################################################################################
# Sphinx settings
#sphinx:
#  config:
#    bibtex_reference_style: numbers
bibtex_bibfiles: [references.bib]
