########################################################################################
# Book settings
title: Основи програмування в "обіймах" Python
author: Громова В.В.
logo: content/images/logo/logo.png

exclude_patterns: [_*, .*, tools, README.md, content/LICENSE.md]

#description: >-
#  Інструкції до виконання лабораторних робіт
#  з дисципліни "Програмування-1. Основи програмування"

#######################################################################################
# Html settings

html:
  favicon: content/images/logo/favicon.ico
  extra_navbar: <a href="mailto:vikvikgrom@gmail.com">Громова В.В.</a>, 2020
  extra_footer: >-
      This page was created by <a href="https://github.com/gasperpaul/python-labs-book/graphs/contributors">community</a>.<br />
      "Python" and Python logos are trademarks or registered trademarks of Python Software Fundation.
  home_page_in_navbar: true
  baseurl: https://gasperpaul.github.io/python-labs-book

#######################################################################################
# Interact link settings
launch_buttons:
  notebook_interface: jupyterlab
  binderhub_url: https://mybinder.org
  thebe: true

repository:
  url: https://github.com/GasperPaul/python-labs-book
  branch: master
  path_to_book: ''

#######################################################################################
# Execution settings
execute:
  execute_notebooks: cache
